stages:
  - test

variables:
  MYSQL_DATABASE: edusoho_test
  MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  SONAR_HOST: http://sonar.codeages.net
  SONAR_TOKEN: 5a1ca03b46f84c2cb97434e9faacc06b1c9e65ab

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - cp app/config/parameters.yml.dist app/config/parameters_test.yml
  - "sed -i 's/\\s*database_host.*/    database_host: mysql/g' app/config/parameters_test.yml"
  - "sed -i 's/\\s*database_name.*/    database_name: edusoho_test/g' app/config/parameters_test.yml"
  - "echo '    redis_host: [redis:6379]' >> app/config/parameters_test.yml"
  - "echo '    redis_timeout: 1' >> app/config/parameters_test.yml"
  - "echo '    redis_reserved: null' >> app/config/parameters_test.yml"
  - "echo '    redis_retry_interval: 100' >> app/config/parameters_test.yml"
  - mkdir web/files
  - mkdir -p app/data/private_files
  - touch app/config/routing_plugins.yml

Unit Test With PHP 5.5:
  stage: test
  image: codeages/ci-php:7.0-15
  services:
    - mysql:5.5
    - redis:latest
  script:
    - phpunit -c app/
  except:
    - tags
    - develop
    - master
    - trigger

Unit Test With PHP 7.0:
  stage: test
  image: codeages/ci-php:7.0-15
  services:
    - mysql:5.5
    - redis:latest
  script:
    - sed -i 's/memory_limit.*/memory_limit = 2048M/g' /etc/php/7.0/phpdbg/php.ini
    - cat /etc/php/7.0/phpdbg/php.ini | grep memory_limit
    - phpdbg -qrr /usr/bin/phpunit --testsuite=unit -c app/ --coverage-text --colors=never --coverage-clover reports/phpunit.coverage.xml --log-junit reports/phpunit.xml
    - echo "sonar.host.url=$SONAR_HOST" >> /opt/sonar-scanner/conf/sonar-scanner.properties
    - echo "sonar.login=$SONAR_TOKEN" >> /opt/sonar-scanner/conf/sonar-scanner.properties
    - /opt/sonar-scanner/bin/sonar-scanner
  only:
    - tags
    - develop
    - master
    - trigger

#Functional Test With 5.5:
#  stage: test
#  image: codeages/ci-php:5.5-5
#  services:
#    - mysql:5.5
#    - redis:latest
#    - selenium/standalone-chrome:latest
#  script:
#    - php-cs-fixer fix --config=.php_cs.dist -v --dry-run --using-cache=no --path-mode=intersection  `git diff --name-only --diff-filter=ACMRTUXB HEAD~..HEAD`
#    - SELENIUM_SERVER_URL="http://selenium__standalone-chrome:4444/wd/hub" phpunit -c tests/Functional
#  only:
#      - tags
#      - develop
#      - master
#      - trigger